### ISSUE TITLE
Hlm backend container keeps crashing 

### ISSUE THREAD

**Issue by sandhyamohanty29** [healenium/kubernetes#3]
we tried to deploy backend., however its keeps on crashing on below error.

2022-10-31 12:11:24.339  INFO 1 - [       main] com.epam.healenium.Application   : Starting Application using Java 1.8.0_212 on hlm-backend-f9b67f487-zlxzg with PID 1 (/healenium-backend.jar started by root in /) 
2022-10-31 12:11:24.342  INFO 1 - [       main] com.epam.healenium.Application   : No active profile set, falling back to 1 default profile: "default" 
2022-10-31 12:11:27.648  INFO 1 - [       main] .RepositoryConfigurationDelegate : Bootstrapping Spring Data JPA repositories in DEFAULT mode. 
2022-10-31 12:11:28.171  INFO 1 - [       main] .RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 513 ms. Found 4 JPA repository interfaces. 
2022-10-31 12:11:30.067  INFO 1 - [       main] o.s.b.w.e.t.TomcatWebServer      : Tomcat initialized with port(s): 7878 (http) 
2022-10-31 12:11:30.140  INFO 1 - [       main] o.a.c.core.StandardService       : Starting service [Tomcat] 
2022-10-31 12:11:30.140  INFO 1 - [       main] o.a.c.core.StandardEngine        : Starting Servlet engine: [Apache Tomcat/9.0.64] 
2022-10-31 12:11:30.443  INFO 1 - [       main] o.a.c.c.C.[.[localhost].[/]      : Initializing Spring embedded WebApplicationContext 
2022-10-31 12:11:30.443  INFO 1 - [       main] rvletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 5982 ms 
2022-10-31 12:11:31.926  INFO 1 - [       main] c.z.hikari.HikariDataSource      : HikariPool-1 - Starting... 
2022-10-31 12:11:32.455  INFO 1 - [       main] c.z.hikari.HikariDataSource      : HikariPool-1 - Start completed. 
2022-10-31 12:11:32.859  INFO 1 - [       main] liquibase.database               : Set default schema name to healenium 
2022-10-31 12:11:33.143  INFO 1 - [       main] liquibase.lockservice            : Successfully acquired change log lock 
2022-10-31 12:11:34.309  INFO 1 - [       main] liquibase.changelog              : Reading from healenium.databasechangelog 
2022-10-31 12:11:34.433  INFO 1 - [       main] liquibase.lockservice            : Successfully released change log lock 
2022-10-31 12:11:34.755  INFO 1 - [       main] o.h.j.internal.util.LogHelper    : HHH000204: Processing PersistenceUnitInfo [name: default] 
2022-10-31 12:11:34.935  INFO 1 - [       main] org.hibernate.Version            : HHH000412: Hibernate ORM core version 5.6.9.Final 
2022-10-31 12:11:35.548  INFO 1 - [       main] o.h.annotations.common.Version   : HCANN000001: Hibernate Commons Annotations {5.1.2.Final} 
2022-10-31 12:11:35.950  INFO 1 - [       main] org.hibernate.dialect.Dialect    : HHH000400: Using dialect: org.hibernate.dialect.PostgreSQLDialect 
2022-10-31 12:11:37.672  WARN 1 - [       main] o.h.m.internal.MetadataContext   : HHH015011: Unable to locate static metamodel field : com.epam.healenium.model.domain.Selector_#nodePathWrapper; this may or may not indicate a problem with the static metamodel 
2022-10-31 12:11:37.682  INFO 1 - [       main] h.e.t.j.p.i.JtaPlatformInitiator : HHH000490: Using JtaPlatform implementation: [org.hibernate.engine.transaction.jta.platform.internal.NoJtaPlatform] 
2022-10-31 12:11:37.693  INFO 1 - [       main] ontainerEntityManagerFactoryBean : Initialized JPA EntityManagerFactory for persistence unit 'default' 
2022-10-31 12:11:39.273  WARN 1 - [       main] rvletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'healingController' defined in URL [jar:file:/healenium-backend.jar!/BOOT-INF/classes!/com/epam/healenium/controller/HealingController.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'healingServiceImpl': Unsatisfied dependency expressed through field 'urlForKey'; nested exception is org.springframework.beans.TypeMismatchException: Failed to convert value of type 'java.lang.String' to required type 'boolean'; nested exception is java.lang.IllegalArgumentException: Invalid boolean value [] 
2022-10-31 12:11:39.274  INFO 1 - [       main] ontainerEntityManagerFactoryBean : Closing JPA EntityManagerFactory for persistence unit 'default' 
2022-10-31 12:11:39.327  INFO 1 - [       main] c.z.hikari.HikariDataSource      : HikariPool-1 - Shutdown initiated... 
2022-10-31 12:11:39.329  INFO 1 - [       main] c.z.hikari.HikariDataSource      : HikariPool-1 - Shutdown completed. 
2022-10-31 12:11:39.332  INFO 1 - [       main] o.a.c.core.StandardService       : Stopping service [Tomcat] 
2022-10-31 12:11:39.361  INFO 1 - [       main] nEvaluationReportLoggingListener : \n \n Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled. 
2022-10-31 12:11:39.449 ERROR 1 - [       main] o.s.boot.SpringApplication       : Application run failed org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'healingController' defined in URL [jar:file:/healenium-backend.jar!/BOOT-INF/classes!/com/epam/healenium/controller/HealingController.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'healingServiceImpl': Unsatisfied dependency expressed through field 'urlForKey'; nested exception is org.springframework.beans.TypeMismatchException: Failed to convert value of type 'java.lang.String' to required type 'boolean'; nested exception is java.lang.IllegalArgumentException: Invalid boolean value []\n 	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:800)\n 	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:229)\n 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1372)\n 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1222)\n 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582)\n 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)\n 	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)\n 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)\n 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)\n 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)\n 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:955)\n 	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918)\n 	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583)\n 	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:147)\n 	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:734)\n 	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:408)\n 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:308)\n 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306)\n 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1295)\n 	at com.epam.healenium.Application.main(Application.java:9)\n 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\n 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n 	at java.lang.reflect.Method.invoke(Method.java:498)\n 	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)\n 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)\n 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)\n 	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65)\n Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'healingServiceImpl': Unsatisfied dependency expressed through field 'urlForKey'; nested exception is org.springframework.beans.TypeMismatchException: Failed to convert value of type 'java.lang.String' to required type 'boolean'; nested exception is java.lang.IllegalArgumentException: Invalid boolean value []\n 	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.resolveFieldValue(AutowiredAnnotationBeanPostProcessor.java:659)\n 	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:639)\n 	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:119)\n 	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:399)\n 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1431)\n 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:619)\n 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)\n 	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)\n 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)\n 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)\n 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)\n 	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)\n 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1391)\n 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1311)\n 	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:887)\n 	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:791)\n 	... 27 common frames omitted\n Caused by: org.springframework.beans.TypeMismatchException: Failed to convert value of type 'java.lang.String' to required type 'boolean'; nested exception is java.lang.IllegalArgumentException: Invalid boolean value []\n 	at org.springframework.beans.TypeConverterSupport.convertIfNecessary(TypeConverterSupport.java:79)\n 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1339)\n 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1311)\n 	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.resolveFieldValue(AutowiredAnnotationBeanPostProcessor.java:656)\n 	... 42 common frames omitted\n Caused by: java.lang.IllegalArgumentException: Invalid boolean value []\n 	at org.springframework.beans.propertyeditors.CustomBooleanEditor.setAsText(CustomBooleanEditor.java:154)\n 	at org.springframework.beans.TypeConverterDelegate.doConvertTextValue(TypeConverterDelegate.java:429)\n 	at org.springframework.beans.TypeConverterDelegate.doConvertValue(TypeConverterDelegate.java:402)\n 	at org.springframework.beans.TypeConverterDelegate.convertIfNecessary(TypeConverterDelegate.java:155)\n 	at org.springframework.beans.TypeConverterSupport.convertIfNecessary(TypeConverterSupport.java:73)\n 	... 45 common frames omitted\n 

How to fix this ? We have deployed this with Helm chart healenium/hlm-backend:3.2.4 image.

**Comment by Alex-Reif** [comment]
Hi @sandhyamohanty29 , please update to actual version and check again.
